version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "7000:7000"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
      - postgres
      - clickhouse
      - redis
    links:
      - postgres:postgres
      - clickhouse:clickhouse
      - redis:redis
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    env_file:
      - .production.env
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhousedata:/var/lib/clickhouse
    restart: always
  redis:
    container_name: redis
    image: redis:alpine
    env_file:
      - .production.env
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis/data
    restart: always
volumes:
  pgdata:
  clickhousedata:
  redisdata: